### PR TITLE
Fix/static ip display

### PR DESCRIPTION
**Pull request by KomelT**
I added `convertIntToIpAddress()` and `convertIpAddressToInt()`  .

It is a little janky but it converts INT to IP:
image

And also IP to INT:
image

The problem is that validator inheritances types from protobuf, so it expects a number instead of a string:
image

Can they be decoupled?

```javascript
export class NetworkValidationIpV4Config {
.
.
.
```

### CODE REVIEW

**Comment by Hunter275** [comment]
@KomelT I'll take a look at this when I'm finished with #266

**Comment by Hunter275** [comment]
@KomelT is this ready for prime time, it seems to be working for me

**Comment by KomelT** [comment]
@Hunter275 great, than merge it.

**Comment by Hunter275** [comment]
Reading from the device works fine but I cannot save

**Pull request merged**
