### PR TITLE
Update Map.tsx

### PR DESCRIPTION
**Pull request by Xfox0ne**
changed the weirdly set default viewstate

### CODE REVIEW

**Comment by garthvh** [comment]
Not sure null island is a better default the Melbourne.

**Comment by Xfox0ne** [comment]
> Not sure null island is a better default the Melbourne.

But zoomed out more, making more of the map visible.

**Comment by sachaw** [comment]
I'd say avoid null island, but keep the zoom level

**Comment by Xfox0ne** [comment]
> I'd say avoid null island, but keep the zoom level

But where else? Setting it to Eurasia would be worse for American, African and Australian users and vice versa.
Maybe we could set the zoom level to show the whole world map, but that would be inefficient, as more map data must be loaded for that.

**Comment by garthvh** [comment]
> > I'd say avoid null island, but keep the zoom level
> 
> But where else? Setting it to Eurasia would be worse for American, African and Australian users and vice versa. Maybe we could set the zoom level to show the whole world map, but that would be inefficient, as more map data must be loaded for that.

leave the default location alone.

**Pull request closed without merging**
