### PR TITLE
PSK Generator

### LINKED ISSUE #261: [Bug]: Update Channel Password flavor text
### Hardware

Not Applicable

### Connection Type

HTTP, Bluetooth, Serial

### Local or Hosted

http://meshtastic.local, https://client.meshtastic.org

### Firmware Version

Any

### Description

This flavor text needs updated to show the different PSK sizes:

image

### Relevant console output

_No response_

### PR DESCRIPTION
**Pull request by Hunter275**
Added a password generator to match iOS ability.

TODO:
Button changes input value ✅ 
PSK length dropdown changes password generation ✅ 
PSK key generation ✅ 
PSK loading from device ✅  
PSK saving to device ✅
PSK length validation ✅

### CODE REVIEW

**Comment by Hunter275** [comment]
To generate a password on iOS:

https://github.com/meshtastic/Meshtastic-Apple/blob/07c1018b538ea3bedd72ed243d9041d723650cb4/Meshtastic/Views/Settings/Channels.swift#L17

We use `SecRandomCopyBytes()` (https://developer.apple.com/documentation/security/1399291-secrandomcopybytes) to create a random input and then we encode it using `base64EncodedString()`

**Review by thebentern — APPROVED** [review]

**Review by garthvh — APPROVED** [review]
Looks good

**Review by rcarteraz — APPROVED** [review]
I fiddled around with it and it's working good for me. Nice work!

**Comment by Hunter275** [comment]
Thanks yall

**Pull request merged**
